name: PHP Compatibility 7.0+
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Test
      run: |
        curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
        export SNIFFS_DIR=/tmp/sniffs
        git clone -b master --depth 1 https://github.com/wimg/PHPCompatibility.git $SNIFFS_DIR
        php phpcs.phar --config-set installed_paths $SNIFFS_DIR
        php phpcs.phar -p -s -v -n . --standard=PHPCompatibility --extensions=php --runtime-set testVersion 7.0-
