name: PHP Syntax
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Test
      run: find . \( -name '*.php' \) -exec php -lf {} \;
