name: WordPress Coding Standards
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Test
      run: |
        curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
        export SNIFFS_DIR=/tmp/sniffs
        git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $SNIFFS_DIR
        php phpcs.phar --config-set installed_paths $SNIFFS_DIR
        php phpcs.phar -p -s -v -n . --standard=WordPress-Core --extensions=php
